CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
WORKERS: 4
USE_AMP: true
AMP_OPT_LEVEL: 'O1'
LOSS: 'ce'

DATASET:
  DATASET: Hammers_N4_M3_RN
  DATASET_DICT: hammers_n30r95_dict.npy
  ROOT: '../data/'
  NUM_CLASSES: 96
MODEL:
  NAME: voxhrnet
  EXTRA:
    STAGE2:
      NUM_MODULES: 2
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 16
      - 32
    STAGE3:
      NUM_MODULES: 2
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 16
      - 32
      - 64
    STAGE4:
      NUM_MODULES: 2
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 16
      - 32
      - 64
      - 128
TRAIN:
  GROUP_NAME:
  - TRAIN
  GROUP_CNT:
  - 18
  BATCH_SIZE_PER_GPU: 1
  BEGIN_EPOCH: 0
  END_EPOCH: 2000
  RESUME: false
  RESUME_STATE_PATH: 'output/checkpoint.pth.tar'
  SAVE_DIR: 'output'
  SAVE_FREQ: 10
  PRINT_FREQ: 10
VALIDATE:
  GROUP_NAME:
  - VALIDATE
  GROUP_CNT:
  - 2
  BATCH_SIZE_PER_GPU: 1
TEST:
  GROUP_NAME:
  - TEST
  GROUP_CNT:
  - 10
  BATCH_SIZE_PER_GPU: 1
  TEST_STATE_PATH: 'output/best.pth.tar'
